### ISSUE TITLE
wrong dimension

### ISSUE THREAD

**Issue by Thornhill-GYL** [isi-nlp/RECAP#2]
when i ran the train_generator with full dataset, i got the following problem.
The expanded size of the tensor (9) must match the existing size (64) at non-singleton dimension 0.  Target sizes: [9].  Tensor sizes: [64]

**Comment by shuailiu6626** [comment]
Hi! Thank you for bringing this to our attention! Could you please share the command you used for training and provide more details about where the error occurs? That will be very helpful to us in identifying the problem. Thank you!

**Comment by Thornhill-GYL** [comment]
thanks for your reply. I just use the same command line in your repo. I already find bugs. 
first of all, 
when running the train_generator.py, 
this part in your generate_utils.py was reported as can't convert numpy to tensor.
the feature[f"{ref_type}_ids"][type_i] = np.concatenate(
                            [feature[f"{ref_type}_ids"][type_i], remainder]
                        ).astype(np.int64)
next, i change this code to torch.cat, but it also has promble which is the issues i comment.
finnally, i find the bug, which because the 10 history sentence are the same length and same content. so i decide to relpace the feature[f"{ref_type}_ids"] with the new feature.
i have figured this out. thanks for your reply.

**Comment by shuailiu6626** [comment]
Thank you for sharing your solution! I'll try to reproduce this issue and update the code later.

**Comment by shuailiu6626** [comment]
We inspected the issue and found that it is fundamentally caused by the wrong version of the datasets package. The specified version is overwritten by installing the evaluate package. To resolve the conflict, we removed the evaluate package from the dependencies and directly use the bleurt package in eval.py (please see commit 72abce061ff7da14fc7f3a7048d2ed1833b909a6 for details).
